# fly.toml app configuration file generated for ticketer on 2024-07-07T18:55:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ticketer'
primary_region = 'ams'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
    APP_ENV = 'production'
    APP_NAME= 'Ticketer'
    APP_DEBUG= 'true'
    OCTANE_SERVER= 'frankenphp'
    LOG_CHANNEL = 'stderr'
    LOG_LEVEL = 'info'
    LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
    BROADCAST_DRIVER= 'log'
    CACHE_DRIVER= 'file'
    FILESYSTEM_DISK= 'local'
    QUEUE_CONNECTION= 'sync'
    SESSION_DRIVER= 'file'
    SESSION_SECURE_COOKIE = 'true'
    VITE_APP_NAME= '${APP_NAME}'



[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
